# Site settings
title: Alan Accurso
email: accurso.alan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Software Engineer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://aaccurso.me" # the base hostname & protocol for your site
twitter_username: aaaccurso
github_username:  aaccurso
github_token: ${{ secrets.GH_TOKEN }}
exclude:
  - node_modules
  - _src

# Build settings
markdown: kramdown

gems:
  - jekyll-gist
  - jekyll-sitemap
